apiVersion: v1
kind: Service
metadata:
  name: your-application-service
spec:
  selector:
    app: your-application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
